### ISSUE TITLE
onMiss is triggered when the key has maps and it shouldn't

### ISSUE THREAD

**Issue by MetalBlueberry** [MetalBlueberry/chkb#3]
```
Do not triggers miss,  ok
    keyMap:
      KEY_CAPSLOCK:
        Tap:
          - action: ChangeLayer
            layerName: base
        Map:
          - keyCode: KEY_LEFTMETA
triggers miss,  bad
    keyMap:
      KEY_CAPSLOCK:
        Tap:
          - action: ChangeLayer
            layerName: base
```
