### ISSUE TITLE
When an action list contains down and then up events, up is ignored.

### ISSUE THREAD

**Issue by MetalBlueberry** [MetalBlueberry/chkb#4]
```
  symbols:
    onMiss:
      - action: ChangeLayer
        layerName: base
      - action: Map
    keyMap:
      KEY_U:
        Map: 
          - action: Nil*
        Tap:
          - action: Down
            keyCode: KEY_LEFTSHIFT
          - keyCode: KEY_8
          - action: Up
            keyCode: KEY_LEFTSHIFT
```
